### ISSUE TITLE
Procrastination

### ISSUE THREAD

**Issue by SerdarAtalay** [abulut96/2E.Planet-Trip#3]
No, literally that's my issue.
And when I mean my, I really mean that it's mine.
Would highly appreciate any tips/warnings about the topic.

**Comment by ugurdogrusoz** [comment]
@SerdarAtalay What is this issue supposed to mean?

**Comment by SerdarAtalay** [comment]
Since we are working with deadlines, I thought this course is a good opportunity to learn and improve time management, which I'm lack of. 
We know that soft skills are as important as hard skills, but is it wrong to discuss about them on Github?

**Comment by ugurdogrusoz** [comment]
The key to time management is doing tasks "regularly". Things become unmanageable when they pile up. That's why we forced you guys to set up regular meetings and asked you to keep meeting logs and have action items (things to do in between meetings). If you still don't meet regularly and "fake" the meeting log, there is nothing we can't do though.

**Comment by SerdarAtalay** [comment]
I am so sorry about this misunderstanding and panic that I've caused, but meeting logs are valid and everything written there is true.

After looking at old projects solved issues, I had this idea to help CS319 later on who take this course, and give them little tips that I've learned throughout my own experience.

This is purely a personal challenge that I'm dealing with, and I thought it would be nice to share with the community.
